categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking change'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: 'Dependency Updates'
    label: 'dependency'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ### Changes

  $CHANGES
