name: Build

on:
  pull_request:
    branches-ignore:
      - develop
      - master
  push:
    branches:
      - develop

jobs:
  build:
    name: Verify build and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Setup Node.js v10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@aem-design'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_ADMIN }}
      
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_ADMIN }}
      
      - name: Lint our source code
        run: npm run lint
      
      - name: Compile TypeScript
        run: npm run build
      
      - name: Run tests
        run: npm test
      
      - name: Get logs if failure
        run: |
          cd /home/runner/.npm/_logs
          cat * */*
        if: failure()
      
      - name: Ensure NPM can package everything up
        run: npm pack --dry-run
