name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: "@aem-design"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run install
        run: |
          npm install
      - name: get logs if failure
        run: |
          cd /home/runner/.npm/_logs
          cat * */*
        if: failure()
      - name: run tests
        run: |
          npm test
      - name: publish package
        run: |
          npm publish
        with:
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
