name: Build

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and test using node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/
          scope: '@aem-design'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_ADMIN }}

      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_ADMIN }}

      - name: Lint our source code
        run: yarn lint

      - name: Compile TypeScript
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:coverage -- --ci --reporters="default"

      - name: Upload tests coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
          fail_ci_if_error: false

      - name: Get logs if failure
        run: |
          cd /home/runner/.npm/_logs
          cat * */*
        if: failure()

      - name: Ensure NPM can package everything up
        run: npm pack --dry-run
